[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    fast: marks tests as fast (run with -m "fast")
    accurate: marks tests for accurate validation (run with -m "accurate")
    comparison: marks tests for scheme comparison (run with -m "comparison")
